# print("Give me some money:")
# input("Give me some money: ")
# money=input("Give me some money: ")
# print(money)
first_money=input("Dosto give me some taka: ")
second_money=input("Father kisu taka deo:")
print(first_money, second_money)
total_money=int(first_money)+int(second_money)
print(total_money)